version: '3.5'

services:
  nginx:
    image: nginxinc/nginx-unprivileged:1.21-alpine
    depends_on:
      - phpfpm
    ports:
      - 8010:80
    volumes:
      - ./.docker/nginx/vhost.conf:/etc/nginx/conf.d/default.conf
      - .:/app

  phpfpm:
    build:
      dockerfile: ./Dockerfile
    volumes:
      - .:/app

  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 8011:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: eav-dev
    volumes:
      - ./.db-data:/var/lib/mysql

  redis:
    image: redis:6-alpine

  wait:
    image: waisbrot/wait
    environment:
      TARGETS: mysql:3306
      TIMEOUT: 300
